### PR TITLE
Adding TravelManager.cpp as basic project in C++

### PR DESCRIPTION
**Pull request by proffapt**
solves #4 

Do add a `hacktoberfest-accepted` label to this PR for it to be accepted in hacktoberfest.

or, add a `hacktoberfest` tag in your repository.

### CODE REVIEW

**Comment by KrunalKharat02** [comment]
please rename folder C++ IN CAPITAL AS MENTIONED IN CONTRIBUTING RULES

**Comment by proffapt** [comment]
@KrunalKharat02 i will do that.
Also look at #8 or Do add a `hacktoberfest-accepted` label to this PR for it to be accepted in hacktoberfest.

**Comment by proffapt** [comment]
@KrunalKharat02 done

**Comment by KrunalKharat02** [comment]
ALRIGHT

**Pull request merged**
